sudo: required
services:
  - docker

before_install:
  - docker build -t gbdotcom/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true gbdotcom/react-test npm test

after_success:
  - docker build -t gbdotcom/multi-client ./client
  - docker build -t gbdotcom/multi-nginx ./nginx
  - docker build -t gbdotcom/multi-server ./server
  - docker build -t gbdotcom/multi-worker ./worker

# Login to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --passowrd-stdin
# Take those images and push them to dockerhub
  - docker push gbdotcom/multi-client
  - docker push gbdotcom/multi-nginx
  - docker push gbdotcom/multi-server
  - docker push gbdotcom/multi-worker
