sudo: required
services:
  - docker

before_install:
  - docker build -t gbdotcom/react_test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true gbdotcom/react-test npm test

after_success:
  - docker build -t gbdotcom/multi-client ./client
  - docker build -t gbdotcom/multi-nginx ./nginx
  - docker build -t gbdotcom/multi-server ./server
  - docker build -t gbdotcom/multi-worker ./worker